version: '3.8'

services:
  signalrchatapp:
    build:
      context: .
      dockerfile: SignalRChatApp/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production